### ISSUE TITLE
Please clarify the instructions for integrating abrader-gms webhook type into this module

### ISSUE THREAD

**Issue by jjarokergc** [voxpupuli/puppet-r10k#623]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 8.1.0
- Ruby: 2.7.0p0
- Distribution: focal
- Module version: 12.1.1

## How to reproduce (e.g Puppet code you use)
Hello,

I have been using version 10.1.1 of this module successfully in puppet7 and am now attempting to upgrade to puppet8 using the latest version of this module, 12.1.1.  The webhook integration is failing and I am not sure how to correctly incorporate the external type, git_webhook, into this module.

What is the correct method to enable gitlab webhooks with this module?  Specifically:
- should the git_webhook type be installed via a puppetfile (which I can't get to work), manually or some other way?
- it appears that Bugfix #607 is required to deploy webhook and I applied it manually.  Is this correct?

Thank you,
Jon

**Comment by jjarokergc** [comment]
This is a comment for anyone considering this module for r10k webhooks.  The r10k setup works ok, but the webhook section is broken.

The documentation includes a reference to another repository, but the '10k::webhook::package' class actually installs webhook-go.  However, there is a bug somewhere that prevents the yaml data from being written for the configuration file.  I gave up trying to refactor it because the data inheritance is brittle.

Here is a simpler alternative using this webhook server: https://github.com/adnanh/webhook

The manifest to install this is:
```
# Class: Webhook
# Installs https://github.com/adnanh/webhook/
# Configures webhook with parameters specified in data yaml
#
#
class profile::puppet::webhook {
  ### Variables
  $w = lookup('webhook::config')    # Webhook Configuration Parameters in Hiera

  ### Install webhook package
  package { 'Webhook':
    ensure => 'present',
    name   => $w['package']['name'],
  }

  service { 'Webhook':
    ensure  => running,
    name    => $w['package']['name'],
    require => Package['Webhook'],
  }

  ### Configure
  file { 'Webhook Config':
    ensure  => file,
    path    => $w['hooks']['file'],
    content => to_json_pretty($w['hooks']['config']),
    notify  => Service['Webhook'],
  }
}
```

The common.yaml data is:
```
...
### Webhook
webhook::config:
  package:
    name: 'webhook'
  hooks:
    file: '/etc/webhook.conf'
    config:
      - id: 'r10k'
        execute-command: '/opt/puppetlabs/puppet/bin/r10k'
        command-working-directory: '/etc/puppetlabs/r10k'
        pass-arguments-to-command:
        - source: 'string'
          name: 'deploy'
        - source: 'string'
          name: 'environment'
        - source: 'string'
          name: '-p'
        include-command-output-in-response: true
        response-message: 'Triggering R10K'
        trigger-rule:
          match:
            type: 'value'
            value: 'r10k'
            parameter:
              source: 'header'
              name: 'X-Gitlab-Token'

...
```

The gitlab webhook configuration must have the correct URL that matches the webhook 'id', such as:
* URL: http://puppet.staging:9000/hooks/r10k
* Secret token: r10k


It is negligent to leave wrong instructions for code because it wastes peoples' time.
